import { defineConfig } from "@pandacss/dev";
import { stonedogStylePreset } from "@stonedogcode/style/preset";

/**
 * This config exists ONLY so `tsc` can resolve `styled-system/*`.
 *
 * The design-system components are typed against the generated `styled-system`
 * types, which are produced per consumer — there is no such package to install.
 * Without a local copy, `tsc` here reports things like "Property 'onClick' does
 * not exist on type StyledButtonProps", which looks like a broken component and
 * is really a missing codegen.
 *
 * No CSS is emitted from this package. The real stylesheet is generated by the
 * CONSUMER, whose panda config includes this package's source — see
 * `apps/web/panda.config.ts` and its guard test. `@stonedogcode/style` keeps a
 * local config for exactly the same reason.
 */
export default defineConfig({
  preflight: false,
  presets: ["@pandacss/preset-base", "@pandacss/preset-panda", stonedogStylePreset({})],
  include: ["./src/**/*.tsx"],
  outdir: "styled-system",
  jsxFramework: "react",
});
